project:
  type: website
  output-dir: docs

website:
  title: "World Geometries"
  navbar:
    left:
      - href: index.qmd
        text: "Index"
      - href: author.qmd
        text: "Author"
      - href: geopolitical_network.qmd
        text: "Geopolitical network"        
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/pew_opi
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


